services:
  db:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: platform
      POSTGRES_DB: si_platform
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
#      - ./pg_config.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
#      - ./log:var/lib/postgresql/data/log